- name: Upload and Push Generated Files to Main Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Configuration officielle pour utiliser le vrai bot natif de GitHub
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        # On force l'ajout des index recréés
        git add -f Packages Packages.gz Packages.bz2 Release
        
        # Commit officiel signé par le système
        git commit -m "Autogen: Refresh repo indexes (.bz2, .gz, Release) [skip ci]" || echo "Aucun changement à commit."
        
        # Push sécurisé via le token du robot
        git push origin main
