- name: Generate Release and Compress Packages
      run: |
        # Nettoyage des anciens index
        rm -f Packages.gz Packages.bz2 Release

        # Création du fichier Release officiel
        echo "Origin: Retro HackLab's Repo" > Release
        echo "Label: Retro HackLab's Repo" >> Release
        echo "Suite: stable" >> Release
        echo "Version: 1.0.0" >> Release
        echo "Codename: ios" >> Release
        echo "Architectures: iphoneos-arm" >> Release
        echo "Components: main" >> Release
        echo "Description: Welcome to Retro HackLab's Repo" >> Release

        # Compression stricte et forcée pour Cydia
        gzip -9fk Packages
        bzip2 -9fk Packages
