name: Deploy Retro HackLab Repo

on:
  push:
    branches:
      - main

# OBLIGATOIRE : Donne les droits d'écriture pour mettre à jour la branche main
permissions:
  contents: write
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Évite les conflits d'historique Git

    - name: Generate Release and Compress Packages
      run: |
        # Installation indispensable de bzip2 pour le robot
        sudo apt-get update && sudo apt-get install -y bzip2

        # Ton code de nettoyage des anciens index
        rm -f Packages.gz Packages.bz2 Release

        # Création du fichier Release officiel (Épuré pour éviter le bug Packages vide)
        echo "Origin: Retro HackLab's Repo" > Release
        echo "Label: Retro HackLab's Repo" >> Release
        echo "Suite: stable" >> Release
        echo "Version: 1.0.0" >> Release
        echo "Codename: ios" >> Release
        echo "Architectures: iphoneos-arm" >> Release
        echo "Description: Welcome to Retro HackLab's Repo" >> Release

        # Compression stricte et forcée pour Cydia
        gzip -9fk Packages
        bzip2 -9fk Packages

    - name: Upload and Push Generated Files to Main Branch
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Ajout forcé des fichiers générés
        git add -f Packages.gz Packages.bz2 Release
        
        # Le [skip ci] évite au robot de s'auto-déclencher à l'infini
        if ! git diff --cached --quiet; then
          git commit -m "Autogen: Update repository indexes (.bz2, .gz, Release) [skip ci]"
          git push origin main
        else
          echo "Aucun changement structurel détecté."
        fi

    - name: Setup Pages
      uses: actions/configure-pages@v5

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: '.'

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
